apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-operator-ui-service-account
  namespace: {{ .Release.Namespace }}
{{- if .Values.imagePullSecrets}}
imagePullSecrets:
  - name: {{ .Values.imagePullSecrets }}
{{- end }}
