apiVersion: v1
kind: Service
metadata:
  name: mongodb-operator-ui-service-loadbalancer
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: mongodb-operator-ui
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
